version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_local
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    ### NE PAS FAIRE CELA SI VOUS METTEZ CE .yml SUR GitHub !
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo_data:
